apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: monitor
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitor
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    app: fluent-bit
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10
    type: RollingUpdate
  minReadySeconds: 0
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
        app: fluent-bit
    spec:
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluent-bit
        image: dockerhub.pentium.network/gde/pentium-fluent-bit-collector:1.0.1-test4
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
        #envFrom:
        #- configMapRef:
            #name: host-info
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - containerPort: 2020
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: time
        hostPath:
          path: /etc/localtime
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
