# see: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
# - secret.yaml

secretGenerator:
- name: pn-faas-secret
  files: 
  - config.json
  type: Opaque
- name: pn-faas-secret-blcks
  files: 
  - config.blcks.json
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true
