kind: Kustomization

bases:
  - ../../../base/jaeger

images:
  - name: jaegertracing/jaeger-collector
    newTag: "1.14.0"
  - name: jaegertracing/jaeger-query
    newTag: "1.14.0"
  - name: jaegertracing/jaeger-agent
    newTag: "1.14.0"

configMapGenerator:
- name: host-info
  behavior: merge
  literals:
  - data01=192.168.89.95

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pentium-jaeger-ingress
  path: patch_ingress.json
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: jaeger-query
  path: patch_query.yaml
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: jaeger-collector
  path: patch_collector.yaml
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: jaeger-ingester
  path: patch_ingester.yaml
