- op: replace
  path: /spec/template/spec/containers/0/env/2
  value:
    name: KAFKA_BROKERS
    value: kafka-0.kafka-svc.platform-workflow-preview:9092,kafka-1.kafka-svc.platform-workflow-preview:9092,kafka-2.kafka-svc.platform-workflow-preview:9092
- op: replace
  path: /spec/template/spec/containers/0/env/7
  value:
    name: ES_SERVER
    value: elasticsearch.platform-workflow-preview
