apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: argocd
  hostPath:
    path: /var/lib/pnetwork/jenkins
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pn.storage.service
          operator: In
          values:
          - "true"
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Released
