apiVersion: v1
kind: Service
metadata:
  name: balances
  namespace: jhow-liu-openfaas-fn
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    faas_function: balances
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    faas_function: balances
  name: balances
  namespace: jhow-liu-openfaas-fn
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      faas_function: balances
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      creationTimestamp: null
      labels:
        faas_function: balances
      name: balances
    spec:
      containers:
      - image: __IMAGE/balances:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/.lock
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: balances
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/.lock
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          procMount: Default
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/openfaas/secrets
          name: balances-projected-secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: balances-projected-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: config.json
                path: config.json
              name: pn-faas-secret
