apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: monitor
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-collector
  namespace: monitor
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    app: fluentd
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10
    type: RollingUpdate
  minReadySeconds: 0
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: dockerhub.pentium.network/gde/pentium-fluentd-collector:1.0.0-test1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
        env:
        - name: POD_NAMESPACE
          value: "*"
        - name: FLUENTD_ALL_NAMESPACE
          value: "corezilla marvinlog platform-workflow-preview workflow-preview workflow-stable"
        - name: FLUENTD_CONTAINERS_LOG_PATH
          value: /var/log/containers/*_$(POD_NAMESPACE)-router-*.log,/var/log/containers/*$(POD_NAMESPACE)-openfaas-fn*.log,/var/log/containers/ofsm-runner-*_$(POD_NAMESPACE)_*.log,/var/log/containers/scripts-runner-*_$(POD_NAMESPACE)_*.log,/var/log/containers/scripts-service-*_$(POD_NAMESPACE)_*.log,/var/log/containers/workflows-eventhandler-*_$(POD_NAMESPACE)_*.log,/var/log/containers/scripts-installer-*_$(POD_NAMESPACE)_*.log,/var/log/containers/cloudkit-*_$(POD_NAMESPACE)_*.log,/var/log/containers/rbac-condition-constructor-*_$(POD_NAMESPACE)_*.log,/var/log/containers/cloudvm-manipulator-*_$(POD_NAMESPACE)_*.log,/var/log/containers/gateone-*_$(POD_NAMESPACE)_*.log,/var/log/containers/sftp-*_$(POD_NAMESPACE)_*.log,/var/log/containers/workflows-templateinstaller-*_$(POD_NAMESPACE)_*.log
        - name: FLUENTD_CONTAINERS_POS_FILE
          value: /var/log/fluentd-collector.log.pos
#        ports:
#        - containerPort: 24224
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: time
        hostPath:
          path: /etc/localtime
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
