apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/monitor
#  - ../openfaas-fn
#  - ../imagetags/platform-workflow-preview

resources:
- namespace.yaml
- clusterRoleBinding.yaml

namespace: platform-workflow-preview

images:
- name: dockerhub.pentium.network/master/pentium-fluentd
  newName: dockerhub.pentium.network/gde/pentium-fluentd
  newTag: 1.1.3-gde.5

#configMapGenerator:
#- name: fluentd-env
#  env: env.txt
#  behavior: merge

#configMapGenerator:
#- name: fluentd-env
#  files:
#  - env.txt

#patchesJson6902:
#- target:
#   group: rbac.authorization.k8s.io
#   version: v1
#   kind: ClusterRoleBinding
#   name: fluentd
#  path: patch_namespace.yaml
#- target:
#   version: v1
#   kind: Namespace
#   name: monitor
#  path: patch_namespace.yaml

#vars:
#- name: SERVICEACCOUNT_NAMESPACE
#  objref:
#   apiVersion: v1
#   kind: ServiceAccount
#   name: fluentd
#  fieldref:
#   fieldPath: metadata.namespace

