kind: Kustomization

bases:
  - ../../../base/tracing

images:
  - name: jaegertracing/jaeger-collector
    newTag: "1.12.0"
  - name: jaegertracing/jaeger-query
    newTag: "1.12.0"
  - name: jaegertracing/jaeger-agent
    newTag: "1.12.0"

configMapGenerator:
- name: host-info
  behavior: merge
  literals:
  - data01=192.168.89.95

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pentium-jaeger-ingress
  path: patch_ingress.json
