dependencies:
  - name: sentry
    version: 1.3.5
    repository: https://kubernetes-charts.storage.googleapis.com/
#  - name: postgresql
#    version: 1.0.0
#    repository: https://kubernetes-charts.storage.googleapis.com/
