dependencies:
  - name: sentry
    version: 1.3.5
    repository: https://kubernetes-charts.storage.googleapis.com/
#  - name: postgresql
#    version: 4.2.1
#    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 7.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
