# helm template --namespace=sentry --name=sentry . > /tmp/sentry.yaml
sentry:
  postgresql:
    enabled: true
    postgresDatabase: sentry
    postgresUser: sentry
    # Only used when internal PG is disabled
    # postgresHost: postgres
    postgresPassword: "good.job"
    # postgresPort: 5432
    imageTag: "9.6"
    persistence:
      enabled: true 
      resourcePolicy: nil
      storageClass: "example-nfs"
  user:
    password: "good.job"
  persistence:
    storageClass: "example-nfs"
  redis:
    enabled: false
    password: "good.job"
    # should be "{{.Release.Name}}-redis-master"
    host: "sentry-redis-master"
redis:
  enabled: false
  password: "good.job"
  usePassword: true
  cluster:
    enabled: false
  volumePermissions:
    enabled: true
  master:
    persistence:
      storageClass: "example-nfs"
