sentry:
  postgresql:
    enabled: true
    postgresDatabase: sentry
    postgresUser: sentry
    # Only used when internal PG is disabled
    # postgresHost: postgres
    # postgresPassword: postgres
    # postgresPort: 5432
    imageTag: "9.6"
    persistence:
      enabled: true 
      resourcePolicy: nil
      storageClass: "example-nfs"
  persistence:
    storageClass: "example-nfs"
  redis:
    enabled: false
    password: "good.job"
    host: "sentry-redis"
redis:
  enabled: false
  password: "good.job"
  usePassword: true
  cluster:
    enabled: false
  volumePermissions:
    enabled: true
  master:
    persistence:
      storageClass: "example-nfs"
