kind: Kustomization

bases:
-  ../../openfaas-fn

images:
# fluentd
- name: dockerhub.pentium.network/master/pentium-fluentd
  newName: dockerhub.pentium.network/gde/pentium-fluentd
  newTag: dev

# openfaas
- name: __IMAGE/commandaccounts
  newName: dockerhub.pentium.network/jhow-gde/commandaccounts
  newTag: 1.0.0
- name: __IMAGE/commandattachments
  newName: dockerhub.pentium.network/jhow-gde/commandattachments
  newTag: 1.0.0
- name: __IMAGE/commandauths
  newName: dockerhub.pentium.network/jhow-gde/commandauths
  newTag: 1.1.0
- name: __IMAGE/commandautocompletes
  newName: dockerhub.pentium.network/jhow-gde/commandautocompletes
  newTag: 1.0.0
- name: __IMAGE/commandbotchannels
  newName: dockerhub.pentium.network/jhow-gde/commandbotchannels
  newTag: 1.0.0
- name: __IMAGE/commandcallbackfailure
  newName: dockerhub.pentium.network/jhow-gde/commandcallbackfailure
  newTag: 1.0.0
- name: __IMAGE/commandcdncontents
  newName: dockerhub.pentium.network/jhow-gde/commandcdncontents
  newTag: 1.0.0
- name: __IMAGE/commandcdns
  newName: dockerhub.pentium.network/jhow-gde/commandcdns
  newTag: 1.0.0
- name: __IMAGE/commandchannels
  newName: dockerhub.pentium.network/jhow-gde/commandchannels
  newTag: 1.0.0
- name: __IMAGE/commandchatbots
  newName: dockerhub.pentium.network/jhow-gde/commandchatbots
  newTag: 1.0.2
- name: __IMAGE/commandcloudaccount
  newName: dockerhub.pentium.network/jhow-gde/commandcloudaccount
  newTag: 1.0.0
- name: __IMAGE/commandcloudproviders
  newName: dockerhub.pentium.network/jhow-gde/commandcloudproviders
  newTag: 1.0.0
- name: __IMAGE/commandcloudtools
  newName: dockerhub.pentium.network/master/commandcloudtools
  newTag: 0.97.1.1559008867
- name: __IMAGE/commanddatabases
  newName: dockerhub.pentium.network/jhow-gde/commanddatabases
  newTag: 1.0.0
- name: __IMAGE/commanddomainresolvers
  newName: dockerhub.pentium.network/jhow-gde/commanddomainresolvers
  newTag: 1.0.0
- name: __IMAGE/commanddomains
  newName: dockerhub.pentium.network/jhow-gde/commanddomains
  newTag: 1.0.0
- name: __IMAGE/commandhosts
  newName: dockerhub.pentium.network/jhow-gde/commandhosts
  newTag: 1.0.0
- name: __IMAGE/commandimproviders
  newName: dockerhub.pentium.network/gde-jhow-liu/commandimproviders
  newTag: 0.1.0
- name: __IMAGE/commandkeypairs
  newName: dockerhub.pentium.network/jhow-gde/commandkeypairs
  newTag: 1.0.0
- name: __IMAGE/commandkms
  newName: dockerhub.pentium.network/jhow-gde/commandkms
  newTag: 1.0.0
- name: __IMAGE/commandplaybooks
  newName: dockerhub.pentium.network/jhow-gde/commandplaybooks
  newTag: 1.0.0
- name: __IMAGE/commandpolicies
  newName: dockerhub.pentium.network/jhow-gde/commandpolicies
  newTag: 1.0.0
- name: __IMAGE/commandprojects
  newName: dockerhub.pentium.network/jhow-gde/commandprojects
  newTag: 1.0.0
- name: __IMAGE/commandrbacroles
  newName: dockerhub.pentium.network/jhow-gde/commandrbacroles
  newTag: 1.0.0
- name: __IMAGE/commandregions
  newName: dockerhub.pentium.network/jhow-gde/commandregions
  newTag: 1.0.0
- name: __IMAGE/commandsubdomains
  newName: dockerhub.pentium.network/jhow-gde/commandsubdomains
  newTag: 1.0.0
- name: __IMAGE/commandtunnels
  newName: dockerhub.pentium.network/jhow-gde/commandtunnels
  newTag: 1.0.0
- name: __IMAGE/commandusers
  newName: dockerhub.pentium.network/jhow-gde/commandusers
  newTag: 1.0.0
- name: __IMAGE/commandworkflowcontroller
  newName: dockerhub.pentium.network/jhow-gde/commandworkflowcontroller
  newTag: 1.0.0
- name: __IMAGE/commandworkflowgc
  newName: dockerhub.pentium.network/jhow-gde/commandworkflowgc
  newTag: 1.0.0
- name: __IMAGE/commandworkflows
  newName: dockerhub.pentium.network/jhow-gde/commandworkflows
  newTag: 1.0.0
- name: __IMAGE/commandworkflowtemplates
  newName: dockerhub.pentium.network/jhow-gde/commandworkflowtemplates
  newTag: 1.0.0
- name: __IMAGE/queryaccounts
  newName: dockerhub.pentium.network/jhow-gde/queryaccounts
  newTag: 1.0.0
- name: __IMAGE/queryautocompletes
  newName: dockerhub.pentium.network/jhow-gde/queryautocompletes
  newTag: 1.0.0
- name: __IMAGE/querybotchannels
  newName: dockerhub.pentium.network/jhow-gde/querybotchannels
  newTag: 1.0.0
- name: __IMAGE/querycdncontents
  newName: dockerhub.pentium.network/jhow-gde/querycdncontents
  newTag: 1.0.0
- name: __IMAGE/querycdns
  newName: dockerhub.pentium.network/jhow-gde/querycdns
  newTag: 1.0.0
- name: __IMAGE/querychannels
  newName: dockerhub.pentium.network/jhow-gde/querychannels
  newTag: 1.0.0
- name: __IMAGE/querychatbots
  newName: dockerhub.pentium.network/jhow-gde/querychatbots
  newTag: 1.0.2
- name: __IMAGE/querycloudaccount
  newName: dockerhub.pentium.network/jhow-gde/querycloudaccount
  newTag: 1.0.0
- name: __IMAGE/querycloudproviders
  newName: dockerhub.pentium.network/jhow-gde/querycloudproviders
  newTag: 1.0.0
- name: __IMAGE/querydatabases
  newName: dockerhub.pentium.network/jhow-gde/querydatabases
  newTag: 1.0.0
- name: __IMAGE/querydatabaseversions
  newName: dockerhub.pentium.network/jhow-gde/querydatabaseversions
  newTag: 1.0.0
- name: __IMAGE/querydomainresolvers
  newName: dockerhub.pentium.network/jhow-gde/querydomainresolvers
  newTag: 1.0.0
- name: __IMAGE/querydomains
  newName: dockerhub.pentium.network/jhow-gde/querydomains
  newTag: 1.0.0
- name: __IMAGE/queryevents
  newName: dockerhub.pentium.network/jhow-gde/queryevents
  newTag: 1.0.0
- name: __IMAGE/queryhosts
  newName: dockerhub.pentium.network/jhow-gde/queryhosts
  newTag: 1.0.0
- name: __IMAGE/queryimproviders
  newName: dockerhub.pentium.network/gde-jhow-liu/queryimproviders
  newTag: 0.1.0
- name: __IMAGE/querykeypairs
  newName: dockerhub.pentium.network/jhow-gde/querykeypairs
  newTag: 1.0.0
- name: __IMAGE/querykms
  newName: dockerhub.pentium.network/jhow-gde/querykms
  newTag: 1.0.0
- name: __IMAGE/queryplaybooklogs
  newName: dockerhub.pentium.network/jhow-gde/queryplaybooklogs
  newTag: 1.0.0
- name: __IMAGE/queryplaybooks
  newName: dockerhub.pentium.network/jhow-gde/queryplaybooks
  newTag: 1.0.0
- name: __IMAGE/querypolicies
  newName: dockerhub.pentium.network/jhow-gde/querypolicies
  newTag: 1.0.0
- name: __IMAGE/queryprojects
  newName: dockerhub.pentium.network/jhow-gde/queryprojects
  newTag: 1.0.0
- name: __IMAGE/queryrbacroles
  newName: dockerhub.pentium.network/jhow-gde/queryrbacroles
  newTag: 1.0.0
- name: __IMAGE/queryregions
  newName: dockerhub.pentium.network/jhow-gde/queryregions
  newTag: 1.0.0
- name: __IMAGE/queryservices
  newName: dockerhub.pentium.network/jhow-gde/queryservices
  newTag: 1.0.0
- name: __IMAGE/querysubdomains
  newName: dockerhub.pentium.network/jhow-gde/querysubdomains
  newTag: 1.0.0
- name: __IMAGE/querysyslogs
  newName: dockerhub.pentium.network/jhow-gde/querysyslogs
  newTag: 1.0.0
- name: __IMAGE/querytags
  newName: dockerhub.pentium.network/jhow-gde/querytags
  newTag: 1.0.0
- name: __IMAGE/querytools
  newName: dockerhub.pentium.network/jhow-gde/querytools
  newTag: 1.0.0
- name: __IMAGE/querytunnels
  newName: dockerhub.pentium.network/jhow-gde/querytunnels
  newTag: 1.0.0
- name: __IMAGE/queryusers
  newName: dockerhub.pentium.network/jhow-gde/queryusers
  newTag: 1.0.0
- name: __IMAGE/querywebsshlogs
  newName: dockerhub.pentium.network/jhow-gde/querywebsshlogs
  newTag: 1.0.0
- name: __IMAGE/queryworkflowlogs
  newName: dockerhub.pentium.network/jhow-gde/queryworkflowlogs
  newTag: 1.0.0
- name: __IMAGE/queryworkflows
  newName: dockerhub.pentium.network/jhow-gde/queryworkflows
  newTag: 1.0.0
- name: __IMAGE/queryworkflowtemplates
  newName: dockerhub.pentium.network/jhow-gde/queryworkflowtemplates
  newTag: 1.0.0
- name: __IMAGE/getdomains
  newName: dockerhub.pentium.network/blcks/dm/getdomains
  newTag: 0.0.4
- name: __IMAGE/syncallcdns
  newName: dockerhub.pentium.network/blcks/cdn/syncallcdns
  newTag: 0.0.0523
- name: __IMAGE/gfwcheck
  newName: dockerhub.pentium.network/blcks/dm/gfwcheck
  newTag: 0.1.05211
- name: __IMAGE/getcdns
  newName: dockerhub.pentium.network/blcks/cdn/getcdns
  newTag: 0.0.0523
- name: __IMAGE/balances
  newName: dockerhub.pentium.network/blcks/account/balances
  newTag: 0.0.0524
- name: __IMAGE/sendmessage
  newName: dockerhub.pentium.network/blcks/im/sendmessage
  newTag: 0.1.0531
