# see: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml
resources:
- k8s-monitor-daemonset.yaml

configMapGenerator:
- name: host-info
  literals:	
  - data01=192.168.89.95
configMapGenerator:
- name: fluentd-env
  files:
  - env.txt
secretGenerator:
- name: fluentd-certs
  files:
  - certs/fluentd.crt
  - certs/fluentd.key

generatorOptions:
  disableNameSuffixHash: true
