# see: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml
kind: Kustomization

bases:
- ../zookeeper
- ../kafka
- ../fluentd
- ../fluent-bit

#configMapGenerator:
#- name: host-info
#  literals:	
#  - data01=192.168.89.95

#
#- name: fluentd-env
#  env: env.txt
#
#- name: fluentd-certs
#  files:
#  - certs/fluentd.crt
#  - certs/fluentd.key
#
# argoCD 的 kustomize 版本還不支援 files
#
# secretGenerator:
# - name: fluentd-certs
#   files:
#   - certs/fluentd.crt
#   - certs/fluentd.key

#patchesJson6902:
#- target:
#   version: v1
#   kind: Secret 
#   name: fluentd-certs
#  path: patch_certs.yaml

generatorOptions:
  disableNameSuffixHash: true
