apiVersion: v1
kind: Service
metadata:
  name: queryevents
  namespace: jhow-liu-openfaas-fn
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    faas_function: queryevents
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    faas_function: queryevents
  name: queryevents
  namespace: jhow-liu-openfaas-fn
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      faas_function: queryevents
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      creationTimestamp: null
      labels: queryevents
      name: queryevents
    spec:
      containers:
      - image: dockerhub.pentium.network/jhow-gde/queryevents:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/.lock
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: queryevents
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/.lock
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          procMount: Default
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/openfaas/secrets
          name: queryevents-projected-secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: queryevents-projected-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: config.json
                path: config.json
              name: pn-faas-secret
