kind: Kustomization

bases:
  - ../../../base/monitor

resources:
- namespace.yaml
- clusterRoleBinding.yaml

namespace: monitor

images:
- name: dockerhub.pentium.network/master/pentium-fluentd
  newName: dockerhub.pentium.network/gde/pentium-fluentd
  newTag: dev

#configMapGenerator:
#- name: fluentd-env
#  env: env.txt
#  behavior: merge
