---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: monitor
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: kafka
  namespace: monitor
spec:
  serviceName: kafka-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - kafka
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 1
               podAffinityTerm:
                 labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                        - zk
                 topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: init-myservice
        image: dockerhub.pentium.network/master/busybox:latest
        # use service port not container port
        command: ['sh', '-c', 'until nc -v -z -w 1 zk-2.zk-svc 2181 ; do echo waiting for myservice; sleep 2; done;']
      - name: sleepforit
        image: dockerhub.pentium.network/master/busybox:latest
        command: ['sh', '-c', 'sleep 5s']
      containers:
      - name: kafka
        image: dockerhub.pentium.network/master/kafka:1.4
        ports:
        - containerPort: 9092
        env:
        - name: ZOOKEEPER
          value: "zk-0.zk-svc:2181,zk-1.zk-svc:2181,zk-2.zk-svc:2181"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOGRETENTION
          value: "24"
        - name: PARTITION_NUMBER
          value: "1"
        volumeMounts:
        - name: log
          mountPath: /tmp
        resources:
          requests:
            memory: "1Gi"
            cpu: 500m
        securityContext:
          privileged: true
#      volumes:
#      - name: log
#        hostPath:
#          path: /opt/kafka
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: log
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: example-nfs
      resources:
        requests:
          storage: 5Gi